# this is a node build
language: node_js

# cache node modules
cache:
  directories:
    - "node_modules"

# install dependencies
install:
  - npm install --silent

# the jobs for building and deplyoing the package
jobs:
  include:
    - stage: build and deploy
      script:
        - npm run declare
        - npm run build
      deploy:
        provider: npm
        skip_cleanup: true
        email: $NPM_EMAIL
        api_key: $NPM_KEY
        on:
          tags: true
          repo: zalari/ngrx-utils
          branch: master