language: node_js

jobs:
  include:
    - stage: build
      script:
        - echo "Build package"
        - npm run build
      if: branch = master
    - stage: npm release
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        api_key: $NPM_API_KEY
        on:
          branch: master
